name: Kali VM image builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    env:
      DEBIAN_FRONTEND: noninteractive

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v4

      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      # Prepare the environment
      - name: Prepare the environment
        run: |
          sudo apt-get update \
          sudo apt-get install -y git debos dosfstools p7zip qemu-utils zerofree \
          git clone https://gitlab.com/kalilinux/build-scripts/kali-vm.git \
          cd ./kali-vm
        
      # Build
      - name: Build the Kali VM image
        run: |
          ./build.sh -v vmware -b kali-last-snapshot -D gnome -s 100 -S everything
          
          
