name: Kali VM Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 验证系统自带容器环境
        run: |
          # 检查是否已安装 docker 和 containerd
          echo "Docker 版本："
          docker --version
          echo "Containerd 版本："
          containerd --version
          # 确保 docker 服务启动
          sudo systemctl start docker
          # 将当前用户加入 docker 组（避免权限问题）
          sudo usermod -aG docker $USER
          # 刷新用户组权限（无需重新登录）
          newgrp docker

      - name: 安装其他依赖工具（不含容器相关）
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-utils \
            kpartx \
            yq \
            parted \
            dosfstools

      - name: 赋予脚本执行权限
        run: |
          chmod +x build.sh
          chmod +x build-in-container.sh

      - name: 容器化构建镜像
        run: |
          # 利用系统自带的 docker 环境执行构建脚本
          ./build-in-container.sh

      - name: 查看构建产物
        run: |
          ls -lh output/

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: kali-vm-image
          path: output/*.img
          retention-days: 7
