name: Kali VM Image Build

# 触发条件：推送到主分支或创建 Pull Request 时
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 构建可能耗时较长，设置超时时间

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖工具
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-utils \
            docker.io \
            kpartx \
            yq \
            parted \
            dosfstools
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: 赋予脚本执行权限
        run: |
          chmod +x build.sh
          chmod +x build-in-container.sh

      - name: 容器化构建镜像
        run: |
          # 使用项目提供的容器化构建脚本
          ./build-in-container.sh

      - name: 查看构建产物
        run: |
          ls -lh output/  # 假设输出文件在 output 目录

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: kali-vm-image
          path: output/*.img  # 上传所有 img 格式的镜像文件
          retention-days: 7  # 产物保留 7 天
