name: Kali VM Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖工具（解决容器包冲突）
        run: |
          sudo apt-get update
          # 先卸载系统自带的 containerd，避免与 docker.io 依赖的 containerd.io 冲突
          sudo apt-get remove -y containerd
          # 强制安装 docker.io 及其依赖（自动处理 containerd.io）
          sudo apt-get install -y \
            qemu-utils \
            docker.io \
            kpartx \
            yq \
            parted \
            dosfstools
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          # 验证 Docker 是否正常启动
          docker --version

      - name: 赋予脚本执行权限
        run: |
          chmod +x build.sh
          chmod +x build-in-container.sh

      - name: 容器化构建镜像
        run: |
          ./build-in-container.sh

      - name: 查看构建产物
        run: |
          ls -lh output/

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: kali-vm-image
          path: output/*.img
          retention-days: 7
