name: Kali Linux VM 自动构建（纯主机环境）

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ARCH: "amd64"
  BRANCH: "kali-last-snapshot"
  VARIANT: "vmware"
  FORMAT: "vmware"
  DESKTOP: "gnome"
  SIZE: "100"  # 进一步减小磁盘大小以加快纯软件模拟构建
  TOOLSET: "default"
  USER_PASS: "kali:kali"
  TIMEZONE: "Asia/Shanghai"
  OUTPUT_DIR: "artifacts"
  DEPLOY_DIR: "releases"
  # 增加QEMU模拟性能的环境变量
  QEMU_CPU: "max"
  QEMU_MEM: "4G"
  # 构建脚本仓库（根据实际情况修改）
  BUILD_SCRIPT_REPO: "https://gitlab.com/kalilinux/build-scripts/kali-vm.git"
  BUILD_SCRIPT_DIR: "kali-vm"

jobs:
  build:
    name: 纯主机环境构建 Kali VM 镜像
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 180  # 延长超时时间，软件模拟构建较慢

    steps:
      - name: 拉取主代码仓库
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 获取Kali VM构建脚本
        run: |
          # 如果当前仓库不包含build.sh，从官方仓库克隆
          if [ ! -f "build.sh" ] && [ ! -f "${BUILD_SCRIPT_DIR}/build.sh" ]; then
            echo "未找到build.sh，从官方仓库克隆..."
            git clone $BUILD_SCRIPT_REPO $BUILD_SCRIPT_DIR
          fi
          
          # 验证构建脚本是否存在
          if [ -f "build.sh" ]; then
            echo "找到build.sh在当前目录"
            BUILD_SCRIPT_PATH="./build.sh"
          elif [ -f "${BUILD_SCRIPT_DIR}/build.sh" ]; then
            echo "找到build.sh在${BUILD_SCRIPT_DIR}目录"
            BUILD_SCRIPT_PATH="./${BUILD_SCRIPT_DIR}/build.sh"
            # 进入构建脚本目录
            cd $BUILD_SCRIPT_DIR
          else
            echo "❌ 未找到build.sh构建脚本"
            exit 1
          fi
          
          # 保存构建脚本路径到环境变量
          echo "BUILD_SCRIPT_PATH=${BUILD_SCRIPT_PATH}" >> $GITHUB_ENV
          echo "当前工作目录: $(pwd)"
          echo "构建脚本路径: ${BUILD_SCRIPT_PATH}"
          ls -la

      - name: 安装主机环境依赖（不含容器组件）
        run: |
          # 彻底更新系统并安装必要工具，移除所有容器相关包
          sudo apt-get update -y
          sudo apt-get upgrade -y
          
          # 先清理可能存在的冲突包
          sudo apt-get remove -y containerd.io containerd docker.io docker-engine docker-ce
          sudo apt-get autoremove -y
          
          # 安装必要工具（不含任何容器相关组件）
          sudo apt-get install -y \
            debos \
            dosfstools \
            p7zip-full \
            qemu-system-x86 \
            qemu-utils \
            zerofree \
            git \
            curl \
            wget \
            unzip \
            parted \
            kpartx \
            debootstrap \
            squashfs-tools \
            xz-utils \
            libguestfs-tools
          
          # 验证QEMU安装和版本
          qemu-system-x86_64 --version
          
          # 确保设备文件权限正确
          sudo chmod 666 /dev/null /dev/zero /dev/random /dev/urandom

      - name: 配置Debos强制软件模拟
        run: |
          # 创建Debos配置文件，优化QEMU参数
          mkdir -p ~/.config/debos
          cat > ~/.config/debos/config.yaml << EOF
          qemu:
            acceleration: none
            cpu: $QEMU_CPU
            memory: $QEMU_MEM
            extra-args: "-no-kvm -machine q35,accel=tcg -smp 2"
          EOF
          cat ~/.config/debos/config.yaml

      - name: 主机环境直接构建镜像
        run: |
          # 显示工作目录和文件列表，用于调试
          echo "当前工作目录: $(pwd)"
          ls -la
          
          # 确保构建脚本有执行权限
          chmod +x $BUILD_SCRIPT_PATH
          
          # 增加系统文件描述符限制，避免构建过程中出现"too many open files"错误
          ulimit -n 4096
          
          # 直接在主机环境运行构建脚本，禁用所有虚拟化加速
          $BUILD_SCRIPT_PATH \
            -a $ARCH \
            -b $BRANCH \
            -v $VARIANT \
            -f $FORMAT \
            -D $DESKTOP \
            -s $SIZE \
            -T $TOOLSET \
            -U $USER_PASS \
            -Z $TIMEZONE \
            --artifactdir $OUTPUT_DIR \
            --disable-kvm \
            --no-container  # 确保不使用任何容器化方式

          # 验证构建结果
          if [ -z "$(ls $OUTPUT_DIR/*.$FORMAT 2>/dev/null)" ]; then
            echo "❌ 镜像构建失败，未找到产物文件"
            exit 1
          else
            echo "✅ 镜像构建成功，产物列表："
            ls -lh $OUTPUT_DIR
          fi

      - name: 压缩镜像产物
        run: |
          mkdir -p $DEPLOY_DIR
          # 如果构建脚本在子目录，需要调整路径
          if [ -d "${BUILD_SCRIPT_DIR}/${OUTPUT_DIR}" ]; then
            OUTPUT_PATH="${BUILD_SCRIPT_DIR}/${OUTPUT_DIR}"
          else
            OUTPUT_PATH="${OUTPUT_DIR}"
          fi
          
          for file in $OUTPUT_PATH/*.$FORMAT; do
            filename=$(basename "$file")
            # 增加压缩线程数加速压缩过程
            7z a -t7z -mmt=4 "$DEPLOY_DIR/${filename}.7z" "$file" -mx=9
            echo "压缩完成：$DEPLOY_DIR/${filename}.7z"
          done
          cd $DEPLOY_DIR
          sha256sum * > SHA256SUMS
          cd ..

      - name: 上传产物到 GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kali-vm-images
          path: ${{ env.DEPLOY_DIR }}/*
          retention-days: 7

      - name: 创建 GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: "Kali VM 纯主机构建 ${{ github.sha }}"
          tag_name: "native-build-${{ github.sha }}"
          body: |
            纯主机环境自动构建产物（基于 commit: ${{ github.sha }}）
            - 架构：${{ env.ARCH }}
            - 桌面环境：${{ env.DESKTOP }}
            - 格式：${{ env.FORMAT }}
            - 构建环境：Ubuntu 22.04 纯主机环境（无容器）
          files: ${{ env.DEPLOY_DIR }}/*
          draft: false
          prerelease: true
